"""netlist.py - render a CircuitIR to ngspice (SPICE3) and VACASK (Spectre).

Also parses the SPICE subcircuit that scikit-rf emits for the universal
macromodel into a CircuitIR, so the *same* IR drives both dialects and the
schematic.  scikit-rf only emits V, R, C, G (VCCS) and F (CCCS) elements, which
is the set handled here.
"""
from __future__ import annotations
import re
from .ir import CircuitIR, Element


def _num(x: float) -> str:
    return f"{x:.10g}"


# --------------------------------------------------------------------------- #
#  Parse the scikit-rf SPICE subcircuit text into a CircuitIR
# --------------------------------------------------------------------------- #
def parse_spice_subckt(text: str, name: str = "s_equivalent") -> CircuitIR:
    ir = CircuitIR(name=name, physical=False)
    for raw in text.splitlines():
        line = raw.strip()
        if not line:
            continue
        if line.startswith("*"):
            ir.comments.append(line.lstrip("* ").rstrip())
            continue
        low = line.lower()
        if low.startswith(".subckt"):
            parts = line.split()
            ir.name = parts[1]
            ir.ports = parts[2:]
            continue
        if low.startswith(".ends") or low.startswith(".end"):
            continue
        tok = line.split()
        k = tok[0][0].upper()
        nm = tok[0]
        if k in ("R", "C", "L", "V"):
            ir.add(Element(k, nm, (tok[1], tok[2]), float(tok[3])))
        elif k in ("G", "E"):
            ir.add(Element(k, nm, (tok[1], tok[2]), float(tok[5]),
                           ctrl=(tok[3], tok[4])))
        elif k == "F":
            ir.add(Element("F", nm, (tok[1], tok[2]), float(tok[4]),
                           ctrl=(tok[3],)))
    return ir


# --------------------------------------------------------------------------- #
#  ngspice  (Berkeley SPICE3)
# --------------------------------------------------------------------------- #
def render_ngspice(ir: CircuitIR) -> str:
    L = [f"* {ir.name} - lumped-element equivalent (ngspice / SPICE3)",
         "* generated by snp2le"]
    L += [f"* {c}" for c in ir.comments[:4]]
    L.append(f".SUBCKT {ir.name} {' '.join(ir.ports)}")
    for e in ir.elements:
        if e.kind in ("R", "C", "L", "V"):
            L.append(f"{e.name} {e.nodes[0]} {e.nodes[1]} {_num(e.value)}")
        elif e.kind in ("G", "E"):
            L.append(f"{e.name} {e.nodes[0]} {e.nodes[1]} "
                     f"{e.ctrl[0]} {e.ctrl[1]} {_num(e.value)}")
        elif e.kind == "F":
            L.append(f"{e.name} {e.nodes[0]} {e.nodes[1]} "
                     f"{e.ctrl[0]} {_num(e.value)}")
    L.append(f".ENDS {ir.name}")
    return "\n".join(L) + "\n"


# --------------------------------------------------------------------------- #
#  VACASK  (Spectre-style netlist)
# --------------------------------------------------------------------------- #
_SPECTRE = {
    "R": lambda e: f"{e.name} ({e.nodes[0]} {e.nodes[1]}) resistor r={_num(e.value)}",
    "C": lambda e: f"{e.name} ({e.nodes[0]} {e.nodes[1]}) capacitor c={_num(e.value)}",
    "L": lambda e: f"{e.name} ({e.nodes[0]} {e.nodes[1]}) inductor l={_num(e.value)}",
    "V": lambda e: f"{e.name} ({e.nodes[0]} {e.nodes[1]}) vsource dc={_num(e.value)}",
    "G": lambda e: (f"{e.name} ({e.nodes[0]} {e.nodes[1]} {e.ctrl[0]} {e.ctrl[1]}) "
                    f"vccs gm={_num(e.value)}"),
    "E": lambda e: (f"{e.name} ({e.nodes[0]} {e.nodes[1]} {e.ctrl[0]} {e.ctrl[1]}) "
                    f"vcvs gain={_num(e.value)}"),
    "F": lambda e: (f"{e.name} ({e.nodes[0]} {e.nodes[1]}) cccs "
                    f"probe={e.ctrl[0]} gain={_num(e.value)}"),
}


def render_vacask(ir: CircuitIR) -> str:
    L = ["// VACASK (Spectre-style) netlist",
         f"// {ir.name} - lumped-element equivalent, generated by snp2le",
         "// NOTE: verify controlled-source syntax (vccs/cccs) against your "
         "VACASK build.",
         "simulator lang=spectre"]
    L += [f"// {c}" for c in ir.comments[:4]]
    L.append(f"subckt {ir.name} ({' '.join(ir.ports)})")
    for e in ir.elements:
        L.append("    " + _SPECTRE[e.kind](e))
    L.append(f"ends {ir.name}")
    return "\n".join(L) + "\n"


def render(ir: CircuitIR, dialect: str) -> str:
    return render_vacask(ir) if dialect == "vacask" else render_ngspice(ir)
