"""netlist.py - render a CircuitIR to ngspice (SPICE3) and VACASK (Spectre).

Also parses the SPICE subcircuit that scikit-rf emits for the universal
macromodel into a CircuitIR, so the *same* IR drives both dialects and the
schematic.  scikit-rf only emits V, R, C, G (VCCS) and F (CCCS) elements, which
is the set handled here.
"""
from __future__ import annotations
import re
from .ir import CircuitIR, Element


def _num(x: float) -> str:
    return f"{x:.10g}"


# Simulator element-value limits.  ngspice floors a resistance below 1e-12 ohm to
# 1e-12 (with the "resistor too small" warning), so we clamp R to that range; this
# matches what the simulator does anyway, so the result is unchanged.  C/L get
# wide safety bounds that leave every realistic value untouched (including the
# universal macromodel's 1 F state capacitors).  V sources and controlled-source
# gains are not clamped.  The clamp is applied to the *model* (see clamp_ir /
# clamp_rows, called from the engine) so the netlist, schematic, values table and
# rebuilt response all describe the same circuit.
_LIMITS = {"R": (1e-12, 1e12), "C": (1e-18, 1e3), "L": (1e-18, 1e3)}
_UNIT_KIND = {"Ω": "R", "F": "C", "H": "L"}


def _clamp(kind: str, value: float) -> float:
    lo_hi = _LIMITS.get(kind)
    if lo_hi is None:
        return value
    lo, hi = lo_hi
    return min(max(value, lo), hi)


def clamp_ir(ir):
    """Clamp every R/L/C element value to the simulator-valid range, in place."""
    for e in ir.elements:
        e.value = _clamp(e.kind, e.value)
    return ir


def clamp_rows(rows):
    """Clamp (label, value, unit) value-table rows to match the clamped model."""
    return [(lab, _clamp(_UNIT_KIND.get(unit, ""), val), unit)
            for lab, val, unit in rows]


def safe_subckt_name(text: str, fallback: str = "s_equivalent") -> str:
    """Turn an arbitrary string (e.g. an export file stem) into a valid SPICE
    subcircuit name: keep letters/digits/underscore, map the rest to '_', and
    avoid a leading digit."""
    name = re.sub(r"[^A-Za-z0-9_]", "_", str(text)).strip("_")
    if not name:
        return fallback
    if name[0].isdigit():
        name = "x" + name
    return name


# --------------------------------------------------------------------------- #
#  Parse the scikit-rf SPICE subcircuit text into a CircuitIR
# --------------------------------------------------------------------------- #
def parse_spice_subckt(text: str, name: str = "s_equivalent") -> CircuitIR:
    ir = CircuitIR(name=name, physical=False)
    for raw in text.splitlines():
        line = raw.strip()
        if not line:
            continue
        if line.startswith("*"):
            ir.comments.append(line.lstrip("* ").rstrip())
            continue
        low = line.lower()
        if low.startswith(".subckt"):
            parts = line.split()
            ir.name = parts[1]
            ir.ports = parts[2:]
            continue
        if low.startswith(".ends") or low.startswith(".end"):
            continue
        tok = line.split()
        k = tok[0][0].upper()
        nm = tok[0]
        if k in ("R", "C", "L", "V"):
            ir.add(Element(k, nm, (tok[1], tok[2]), float(tok[3])))
        elif k in ("G", "E"):
            ir.add(Element(k, nm, (tok[1], tok[2]), float(tok[5]),
                           ctrl=(tok[3], tok[4])))
        elif k == "F":
            ir.add(Element("F", nm, (tok[1], tok[2]), float(tok[4]),
                           ctrl=(tok[3],)))
    return ir


# --------------------------------------------------------------------------- #
#  ngspice  (Berkeley SPICE3)
# --------------------------------------------------------------------------- #
def render_ngspice(ir: CircuitIR, pdk=None) -> str:
    L = [f"* {ir.name} - lumped-element equivalent (ngspice / SPICE3)",
         "* generated by snp2le"]
    if pdk is not None:
        L.append(f"* PDK: {pdk.display_name} ({pdk.key}) - {pdk.vendor}")
    L += [f"* {c}" for c in ir.comments[:4]]
    L.append(f".SUBCKT {ir.name} {' '.join(ir.ports)}")
    for e in ir.elements:
        if e.kind in ("R", "C", "L", "V"):
            L.append(f"{e.name} {e.nodes[0]} {e.nodes[1]} {_num(e.value)}")
        elif e.kind in ("G", "E"):
            L.append(f"{e.name} {e.nodes[0]} {e.nodes[1]} "
                     f"{e.ctrl[0]} {e.ctrl[1]} {_num(e.value)}")
        elif e.kind == "F":
            L.append(f"{e.name} {e.nodes[0]} {e.nodes[1]} "
                     f"{e.ctrl[0]} {_num(e.value)}")
    L.append(f".ENDS {ir.name}")
    return "\n".join(L) + "\n"


# --------------------------------------------------------------------------- #
#  VACASK  (Spectre-style netlist)
# --------------------------------------------------------------------------- #
_SPECTRE = {
    "R": lambda e: f"{e.name} ({e.nodes[0]} {e.nodes[1]}) resistor r={_num(e.value)}",
    "C": lambda e: f"{e.name} ({e.nodes[0]} {e.nodes[1]}) capacitor c={_num(e.value)}",
    "L": lambda e: f"{e.name} ({e.nodes[0]} {e.nodes[1]}) inductor l={_num(e.value)}",
    "V": lambda e: f"{e.name} ({e.nodes[0]} {e.nodes[1]}) vsource dc={_num(e.value)}",
    "G": lambda e: (f"{e.name} ({e.nodes[0]} {e.nodes[1]} {e.ctrl[0]} {e.ctrl[1]}) "
                    f"vccs gm={_num(e.value)}"),
    "E": lambda e: (f"{e.name} ({e.nodes[0]} {e.nodes[1]} {e.ctrl[0]} {e.ctrl[1]}) "
                    f"vcvs gain={_num(e.value)}"),
    "F": lambda e: (f"{e.name} ({e.nodes[0]} {e.nodes[1]}) cccs "
                    f"probe={e.ctrl[0]} gain={_num(e.value)}"),
}


def render_vacask(ir: CircuitIR, pdk=None) -> str:
    if pdk is not None and not pdk.vacask:
        return (f"// VACASK netlist not available for PDK '{pdk.display_name}' "
                f"({pdk.key}).\n"
                "// VACASK (Spectre) output is currently only supported for the "
                "IHP PDKs.\n")
    L = ["// VACASK (Spectre-style) netlist",
         f"// {ir.name} - lumped-element equivalent, generated by snp2le",
         "// NOTE: verify controlled-source syntax (vccs/cccs) against your "
         "VACASK build.",
         "simulator lang=spectre"]
    if pdk is not None:
        L.append(f"// PDK: {pdk.display_name} ({pdk.key}) - {pdk.vendor}")
    L += [f"// {c}" for c in ir.comments[:4]]
    L.append(f"subckt {ir.name} ({' '.join(ir.ports)})")
    for e in ir.elements:
        L.append("    " + _SPECTRE[e.kind](e))
    L.append(f"ends {ir.name}")
    return "\n".join(L) + "\n"


def render(ir: CircuitIR, dialect: str, pdk=None) -> str:
    return (render_vacask(ir, pdk) if dialect == "vacask"
            else render_ngspice(ir, pdk))
